baseURL = 'https://thangvd2312.github.io/'
relativeURLs = true
uglyURLs = false
languageCode = 'vn-VN'
title = 'jerry'
theme = "archie"


[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/vu.van.thang.810982/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/thangvd2312/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/thang-vu-b916b6119/"