baseURL = 'https://thangvd2312.github.io/'
relativeURLs = true
uglyURLs = false
languageCode = 'vn-VN'
title = "jerry's notes"
theme = "archie"



[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/vu.van.thang.810982/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/thangvd2312/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/thang-vu-b916b6119/"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4